### ISSUE TITLE
Regression in 20260506.1: generic substitution lost through method-returned mapped type

### ISSUE THREAD

**Issue by Apollon77** [microsoft/typescript-go#3747]
## Summary

A generic substitution that worked in tsgo `7.0.0-dev.20260505.1` and earlier
no longer resolves correctly in `7.0.0-dev.20260506.1` and later when the call
goes through:

```
class Foo {
    method<T extends SomeInterface>(arg: T): MappedType<T>;
}
```

At call site, `instance.method(ConcreteClass).someMember()` resolves the
mapped-type's value to the **constraint-default** form (`MappedType<any>` in
effect) rather than substituting `T = typeof ConcreteClass`. Direct type
instantiation `MappedType<typeof ConcreteClass>` still resolves correctly.

## IDE vs CLI divergence

- **tsgo IDE-mode** (LSP) resolves correctly: shows the substituted type.
- **tsgo CLI** and **tsc 6.0.3 CLI** both show the unsubstituted form.

PR #3695 ("Fix inference from never into union targets") states it aligns
tsgo with Strada code+behavior, but tsc 6.0.3 has the same regression at CLI
level (different from its language-service path).

## Bisect

- `7.0.0-dev.20260505.1`: works
- `7.0.0-dev.20260506.1`: regressed

Likely culprit: PR #3695.

## Repro using matter.js

```ts
// install: npm i @matter/node@^0.17 @typescript/native-preview@7.0.0-dev.20260507.1
import { OnOffClient } from "@matter/node/behaviors/on-off";
import type { Endpoint } from "@matter/node";

declare const ep: Endpoint;
const cmds = ep.commandsOf(OnOffClient);

async function test() {
    await cmds.toggle();   // tsgo CLI: error TS2554 "Expected 1-2 arguments, but got 0"
}
```

Run `tsgo --noEmit` against this. Expected: clean. Actual: TS2554.

The relevant types are:

```ts
// matter.js: packages/node/src/endpoint/properties/Commands.ts
interface Command<C extends (arg: unknown) => unknown = (arg: unknown) => unknown> {
    (
        ...args: Parameters<C> extends []
            ? [input?: void, context?: CommandContext]
            : [input: Parameters<C>[0], context?: CommandContext]
    ): Promise<Awaited<ReturnType<C>>>;
}

type OfBehavior<T extends Behavior.Type> = {
    [K in keyof InstanceType<T>]: InstanceType<T>[K] extends (arg: any) => any
        ? Command<InstanceType<T>[K]>
        : never;
};

// matter.js: packages/node/src/endpoint/Endpoint.ts
class Endpoint<T extends EndpointType = EndpointType.Empty> {
    commandsOf<T extends Behavior.Type>(type: T) {
        return ... as Commands.OfBehavior<T>;
    }
}
```

`OnOffClient` is a constructor for `CompleteInstance<typeof ClusterBehavior, OnOff>`
which has `toggle(): MaybePromise` (no params).

When probed:
- `Commands.OfBehavior<typeof OnOffClient>['toggle']`
  → tsc/tsgo CLI: `Command<() => MaybePromise>` ✅
  → call signature: `(input?: void, context?: ...) => Promise<void>` ✅
- `ep.commandsOf(OnOffClient)['toggle']` (same expression via method)
  → tsc/tsgo CLI: `Command<any>` ❌
  → call signature: `(input: unknown, context?: ...) => Promise<...>` ❌
  → tsgo IDE-mode: `Command<() => MaybePromise>` ✅

The IDE-mode result is the correct one — the CLI loses `T = typeof OnOffClient`.

## Why a synthetic minimal repro is elusive

I attempted to reduce this to a synthetic minimal `.ts` with no matter.js
imports. None of my attempts (constructor interfaces with multiple readonly
props, generic intersections, `Identity<T> = T` self-reference, large
method-keyspaces) reproduced the failure. The trigger appears to involve
the deep intersection used in `ClusterBehavior.CompleteInstance<B, NS>`:

```ts
type CompleteInstance<B extends Behavior.Type, N extends ClusterTyping> = ClusterBehavior &
    Omit<
        InstanceType<B>,
        | "cluster" | "state" | "events" | "initialize"
        | typeof Symbol.asyncDispose
        | keyof ClusterInterface.MethodsOf<ClusterInterface.InterfaceOf<B>>
        | keyof ExtensionInterfaceOf<B>
    > &
    ClusterInterface.AllMethodsOf<N> &
    ExtensionInterfaceOf<B> & { ... };
```

If you'd like, I can offer further bisection on the matter.js side to narrow
the exact intersection shape that triggers it.

## Workaround

Pin tsgo via npm overrides:

```json
{
  "overrides": {
    "@typescript/native-preview": "7.0.0-dev.20260505.1"
  }
}
```

**Comment by Andarist** [comment]
Please prepare a self-contained repro that somebody could investigate. This kind of an issue should be easily reproducible with code fitting a TS playground.

**Comment by Apollon77** [comment]
I've spent significant effort trying to reduce this to one and so far cannot - also Claude can not find a manageable way to do so.

The behavior only surfaces when type checking against the matter.js **source**
(via `customConditions: ["dev-types"]`, which makes `@matter/*` resolve to its `.ts` files).
Published `.d.ts` files do **not** trigger it — the generic substitution is already baked in,
so a consumer just running `tsgo` against `import { OnOffClient } from "@matter/node"` cannot
reproduce.

There's something in matter.js's actual source — likely the `ClusterBehavior.CompleteInstance<B, N>`
chain or its transitive deps in `ClusterInterface` / `ClusterType` — that I cannot identify just
by reading.

## Self-contained repro using the matter.js repo

Bug reproduces against checked-out source, not published packages. Steps (validated):

```bash
git clone https://github.com/matter-js/matter.js.git
cd matter.js
git checkout main

# pin the broken tsgo via root package.json overrides
node -e '
  const fs=require("fs");
  const p=JSON.parse(fs.readFileSync("package.json","utf8"));
  p.overrides=p.overrides||{};
  p.overrides["@typescript/native-preview"]="7.0.0-dev.20260507.1";
  fs.writeFileSync("package.json", JSON.stringify(p,null,4));
'
npm install

# this fails (tsgo lives under js-tools' node_modules)
node node_modules/@nacho-iot/js-tools/node_modules/@typescript/native-preview/bin/tsgo.js \
    -p packages/node/test/tsconfig.json
```

Expected: clean.
Actual on `7.0.0-dev.20260506.1` and later: 42 errors. Sampling:

```
packages/node/test/node/ClientInvokeTest.ts(42,37): error TS2554: Expected 1-2 arguments, but got 0.
packages/node/test/behavior/cluster/ClusterNarrowingTypingTest.ts(256,34):
  error TS1360: Type 'OfBehavior<T_1>' does not satisfy the expected type '{ setpointRaiseLower: unknown; }'.
```

Pin `7.0.0-dev.20260505.1` instead of `.20260507.1`: clean.

## Probed types (via `extends infer X` tricks)

- `Commands.OfBehavior<typeof OnOffClient>['toggle']` (direct type instantiation)
  → tsc 6.0.3 / tsgo CLI: `Command<() => MaybePromise>` ✅
  → call signature: `(input?: void, context?: ...) => Promise<void>` ✅
- `(typeof ep.commandsOf(OnOffClient))['toggle']` (same expression via method call)
  → tsc 6.0.3 / tsgo CLI: `Command<any>` ❌
  → call signature: `(input: unknown, context?: ...) => Promise<...>` ❌
  → tsgo IDE-mode (LSP): `Command<() => MaybePromise>` ✅

The IDE-mode result is the correct one — both CLIs lose `T = typeof OnOffClient` somewhere in
the method-call inference path.

If anyone has ideas how to better look at that I am more then open to help.

**Comment by RyanCavanaugh** [comment]
Copilot analysis below, which appears to be correct. Can you turn off `skipLibCheck` in the consuming project to confirm?

----

## Root Cause: Declaration Emit Bug (Not Inference)

This is **not** an inference or `never`-handling bug as initially suspected. It's a **declaration emit bug** where shadowed type parameters are incorrectly renamed in the return type but not in the parameter declaration.

## Minimal Repro

**`src/index.ts`**
```ts
export class Container<T> {
    method<T>(arg: T) {
        return arg;
    }
}
```

**`src/tsconfig.json`**
```json
{
    "compilerOptions": {
        "target": "es2022",
        "module": "node16",
        "moduleResolution": "node16",
        "strict": true,
        "composite": true,
        "declaration": true,
        "emitDeclarationOnly": true,
        "outDir": "../dist"
    }
}
```

**`test/test.ts`**
```ts
import { Container } from "../src/index.js";

const c = new Container<number>();
const result = c.method("hello"); // should infer string, fails with T_1 error
```

**`test/tsconfig.json`**
```json
{
    "compilerOptions": {
        "target": "es2022",
        "module": "node16",
        "moduleResolution": "node16",
        "strict": true,
        "noEmit": true
    },
    "references": [{ "path": "../src" }]
}
```

Build with: `tsgo --build test/tsconfig.json --force`

## What Happens

**Bad (7.0.0-dev.20260507.1)** emits:
```ts
export declare class Container<T> {
    method<T>(arg: T): T_1;  // ← T_1 is never declared!
}
```

**Good (7.0.0-dev.20260505.1)** emits:
```ts
export declare class Container<T> {
    method<T>(arg: T): T;    // ← correct
}
```

The `T_1` is undeclared, causing `TS2304: Cannot find name 'T_1'` in the consumer.

## Conditions for the Bug

All three are required:
1. **Class has a type parameter `T`**
2. **Method shadows it with its own type parameter `T`** (same name)
3. **Method return type is inferred** (no explicit annotation)

If any condition is removed, the bug does not trigger:
- Rename the method's type parameter to `U` → works fine
- Add an explicit return type annotation → works fine
- Remove the class type parameter → works fine

## Regression Range

- **Good**: `7.0.0-dev.20260505.1`
- **Bad**: `7.0.0-dev.20260507.1`
- Suspected culprit: PR #3695 ("Fix inference from never into union targets"), which likely changed type resolution behavior that the declaration emitter's type parameter renaming logic depends on.

**Comment by RyanCavanaugh** [comment]
I don't know why I asked, this is trivial to verify myself 😅. This was broken in `7.0.0-dev.20260506.1` but is since fixed as of `7.0.0-dev.20260514.1`, output was
```ts
export declare class Container<T> {
    method<T>(arg: T): T_1;
}
```
but is now
```ts
export declare class Container<T> {
    method<T>(arg: T): T;
}
```
which matches Strada and is correct.

@Apollon77 please confirm on latest, thanks

**Comment by Apollon77** [comment]
Yes I verified it fixing my issue. Thanks a lot!
