### ISSUE TITLE
Type inference broken with rxjs combineLatest

### ISSUE THREAD

**Issue by mattlewis92** [microsoft/typescript-go#1220]
We are trying out the typescript go port on our massive (100mb+) repo, and only ran into 3 common issues with typechecking 🥳 Filing the first one here:

Minimal repro (that compiles with typescript 5.8)

```
import {combineLatest, of} from "rxjs";

const observables = {
    foo: of('foo'),
}

combineLatest(observables).subscribe(({foo}) => {});
```

Output with tsgo:
```
combine-latest-object-inference/index.ts:7:40 - error TS2339: Property 'foo' does not exist on type '[unknown]'.

7 combineLatest(observables).subscribe(({foo}) => {
                                         ~~~

Found 1 error in combine-latest-object-inference/index.ts:7
```

Minimal repro can be run here: https://github.com/mattlewis92/ts-go-issues-repros

**Comment by Andarist** [comment]
Could you minimize those further? An ideal minimal repro case wouldn't rely on any external packages

**Comment by mattlewis92** [comment]
Sure thing, I can try to make it smaller

**Comment by mattlewis92** [comment]
I'm struggling to extract a repro from the library as the types are all highly coupled together, but I did find that the root cause of the issue is this deprecated overload, deleting it fixes the type issue when typechecking with tsgo:

https://github.com/ReactiveX/rxjs/blob/e5351d02e225e275ac0e497c7b66eaa5f0c88791/src/internal/observable/combineLatest.ts#L48-L49

**Comment by Andarist** [comment]
```ts
// @strict: true
// @target: esnext
// @noEmit: true

declare global {
  interface SymbolConstructor {
    readonly observable: symbol;
  }
}

interface Unsubscribable {
  unsubscribe(): void;
}

interface Subscribable<T> {
  subscribe(observer: ((value: T) => void)): Unsubscribable;
}

interface InteropObservable<T> {
  [Symbol.observable]: () => Subscribable<T>;
}

declare class Observable<T> implements Subscribable<T> {
  subscribe(
    observer?: ((value: T) => void),
  ): Unsubscribable;
}

type ObservedValueOf<O> = O extends ObservableInput<infer T> ? T : never;

type ObservableInput<T> = Observable<T> | InteropObservable<T>;

type ObservableInputTuple<T> = {
  [K in keyof T]: ObservableInput<T[K]>;
};

declare function combineLatest<A extends readonly unknown[]>(
  ...sources: [...ObservableInputTuple<A>]
): Observable<A>;
declare function combineLatest<T extends Record<string, ObservableInput<any>>>(
  sourcesObject: T,
): Observable<{ [K in keyof T]: ObservedValueOf<T[K]> }>;

declare const observables: { foo: Observable<string> };

combineLatest(observables).subscribe(({ foo }) => {});

export {};
```

**Comment by Andarist** [comment]
I thiiink it's a duplicate (sort of) of https://github.com/microsoft/typescript-go/issues/1212 . The other issue is about declaration merge issue but the root cause is that Corsa currently keeps properties with `symbol` type defined on `SymbolConstructor` as `symbol`s - Strada "widened" them to `unique symbol`s. You can see the error goes away with this change:
```diff
declare global {
  interface SymbolConstructor {
-    readonly observable: symbol;
+    readonly observable: unique symbol;
  }
}
```

This is being discussed/fixed [here](https://github.com/microsoft/typescript-go/pull/1235). cc @jakebailey @LukeAbby

**Comment by mattlewis92** [comment]
Built https://github.com/microsoft/typescript-go/pull/1235 locally and confirmed this does indeed fix the issue 🥳
