### ISSUE TITLE
`erasableSyntaxOnly` not supported

### ISSUE THREAD

**Issue by indooorsman** [microsoft/typescript-go#911]
```bash
tsgo -p ./tsconfig.json 
tsconfig.json:28:5 - error TS5023: Unknown compiler option 'erasableSyntaxOnly'.

28     "erasableSyntaxOnly": true,
       ~~~~~~~~~~~~~~~~~~~~

Found 1 error in tsconfig.json:28
```

**Comment by jakebailey** [comment]
This is expected; the version of the compiler supported is not 5.8, it's "some random revision from a bit ago" which you can see in: https://github.com/microsoft/typescript-go/tree/main/_submodules

**Comment by indooorsman** [comment]
@jakebailey I see. Thank you.

**Comment by theoludwig** [comment]
Might be worth to keep this issue open, until it's working?

> This is expected; the version of the compiler supported is not 5.8, it's "some random revision from a bit ago" which you can see in: [`main`/_submodules](https://github.com/microsoft/typescript-go/tree/main/_submodules?rgh-link-date=2025-05-22T19%3A03%3A07.000Z)

From my understanding, it is on the roadmap that typescript-go will be eventually updated to the latest version of the Strada compiler. So hopefully, typescript-go will support `erasableSyntaxOnly` soon.

**Comment by jjanie00** [comment]
Still not working in 5.8.3, options is ignored. Looking forward to this being implemented!

**Comment by jakebailey** [comment]
This was fixed in the above linked PR. What isn't working?

**Comment by jjanie00** [comment]
Thanks for the clarifacation !
I see the fix is in typescript-go, but I'm using the official TypeScript compiler (tsc 5.8.3). 
Is this feature planned for the main tsc as well ?

**Comment by jakebailey** [comment]
Yes, 5.8 is the first release it was available in. https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-8.html#the---erasablesyntaxonly-option
