### ISSUE TITLE
Unable to import from declaration files from dependencies in node_modules

### ISSUE THREAD

**Issue by mattlewis92** [microsoft/typescript-go#1221]
Minimal repro (that compiles with typescript 5.8)

```
import { Countries } from 'libphonenumber-js/types';
```

Output with tsgo
```
dependency-type-import/index.ts:1:27 - error TS2307: Cannot find module 'libphonenumber-js/types' or its corresponding type declarations.

1 import { Countries } from 'libphonenumber-js/types';
                            ~~~~~~~~~~~~~~~~~~~~~~~~~

Found 1 error in dependency-type-import/index.ts:1
```

Minimal repro can be run here: https://github.com/mattlewis92/ts-go-issues-repros

**Comment by lukeapage** [comment]
Duplicate of https://github.com/microsoft/typescript-go/issues/982
