### ISSUE TITLE
Object literal may only specify known properties, and 'property' does not exist in type SomeType

### ISSUE THREAD

**Issue by 7nik** [microsoft/typescript-go#1761]
## Steps to reproduce

```ts
function normalise_trace_logs(logs: any[]) {
	let normalised = [];

    normalised.push({ log: logs[0] });
    normalised.push({ log: logs[1], highlighted: logs[1].includes('%c') });

	return normalised;
}

function equal<T>(_actual: T, _expected: T): void {}

equal(normalise_trace_logs([]), [
    { log: 'effect' },
    { log: '$derived', highlighted: true },
    { log: 'double', highlighted: false },
    { log: 4 },
]);
```

## Behavior with `typescript@5.8`

No errors

## Behavior with `tsgo`

```
src/main.ts:14:24 - error TS2353: Object literal may only specify known properties, and 'highlighted' does not exist in type '{ log: any; }'.

14     { log: '$derived', highlighted: true },
                          ~~~~~~~~~~~

src/main.ts:15:22 - error TS2353: Object literal may only specify known properties, and 'highlighted' does not exist in type '{ log: any; }'.

15     { log: 'double', highlighted: false },
                        ~~~~~~~~~~~


Found 2 errors in the same file, starting at: src/main.ts:14
```

---

Context: another error that appeared in the TSGo CI check on the Svelte repo.
Seems to be caused by #1759

**Comment by ahejlsberg** [comment]
Hmm, yeah, that's unintended. Looks like the issue is the stricter check in #1759 for fresh object literal target types instead of just all object literal types. In the issue repro, the object literal types are no longer fresh by the time we relate them. It's easy to switch the check back to the way it was, I'll put up a PR.
