### PR TITLE
Keep dependent destructuring narrowing during re-entrant checks

### LINKED ISSUE #4572: Overloaded assertion in inferred-return function expression loses destructured discriminant narrowing
# Overloaded assertion in inferred-return function expression loses destructured discriminant narrowing for returned property

## Steps to reproduce

Repository: https://github.com/adri1wald/typescript-v6-v7-narrowing-repro

Minimal failing code:

```ts
type State =
  | {
      status: 'ready'
      payload: {
        value?: string
      }
    }
  | {
      status: 'pending'
      payload?: undefined
    }

declare function getState(): State

declare function assert(
  condition: boolean,
): asserts condition

declare function assert(
  condition: boolean,
  message: string,
): asserts condition

const readValue = () => {
  const { status, payload } = getState()

  if (status !== 'ready') {
    throw new Error('Value is not ready.')
  }

  assert(payload.value !== undefined)

  return payload.value
}
```

Config:

```json
{
  "compilerOptions": {
    "noEmit": true,
    "strict": true
  },
  "include": ["src/repro.ts"]
}
```

Commands:

```sh
pnpm install
pnpm run check:ts6
pnpm run check:ts7
pnpm run check:controls
```

The control cases in `src/control-cases.ts` all pass with both compilers. They narrow the discrepancy to this shape:

- the state is narrowed through correlated destructuring: `const { status, payload } = getState()`
- `status !== 'ready'` exits before the assertion
- an overloaded assertion function checks `payload.value`
- the enclosing function is a function expression or arrow function with no syntactic return type annotation
- the function directly returns the destructured `payload` value or property

Nearby cases that pass with `tsgo`:

- a single assertion signature
- a single assertion signature with an optional message parameter
- the same overloaded assertion in a function declaration
- the same overloaded assertion in an arrow function with a syntactic return type annotation
- the same overloaded assertion followed by an intermediate `const value: string = payload.value`
- the same overloaded assertion using the original `state` object instead of correlated destructuring
- an inline guard instead of an assertion function
- the same overloaded assertion when the narrowed `payload` value is not returned

## Behavior with `typescript@6.0`

No errors.

```text
$ pnpm run check:ts6
$ tsc6 -p tsconfig.json --pretty false --noEmit
```

The control cases also pass:

```text
$ pnpm run check:controls:ts6
$ tsc6 --ignoreConfig --strict --noEmit --pretty false src/control-cases.ts
```

## Behavior with `tsgo`

`tsgo` reports `payload` as possibly undefined in the assertion argument:

```text
$ pnpm run check:ts7
$ tsc -p tsconfig.json --pretty false --noEmit
src/repro.ts(31,10): error TS18048: 'payload' is possibly 'undefined'.
```

After this guard:

```ts
if (status !== 'ready') {
  throw new Error('Value is not ready.')
}
```

the remaining union member is the `'ready'` member, where `payload` is defined.

The control cases pass with `tsgo`:

```text
$ pnpm run check:controls:ts7
$ tsc --ignoreConfig --strict --noEmit --pretty false src/control-cases.ts
```

I also checked the current nightly:

```text
$ pnpm --package=typescript@next dlx tsc --version
Version 7.1.0-dev.20260708.3

$ pnpm --package=typescript@next dlx tsc --ignoreConfig --strict --noEmit --pretty false src/repro.ts
src/repro.ts(31,10): error TS18048: 'payload' is possibly 'undefined'.
```

### LINKED ISSUE #4613: Exhaustive switch on co-narrowed tuple's `.length` does not terminate fallthrough control flow (works in TS 6.0)
## Steps to reproduce

Compile the following with `tsc --strict --noEmit` (no other options needed; also reproduces with default options):

```ts
type F =
    | readonly [0, readonly [number]]
    | readonly [0 | 1, readonly [number, number]]
    | readonly [1, readonly [number, number, number]]

const f = ([i, x]: F): undefined => {
    switch (i) {
        case 0: {
            // `x` is narrowed to `readonly [number] | readonly [number, number]`,
            // so `x.length` is `1 | 2` and this inner switch is exhaustive;
            // the end of `case 0` is therefore unreachable:
            switch (x.length) {
                case 1: case 2: return undefined
            }
        }
        case 1: {
            // direct entry: `x` is `readonly [number, number] | readonly [number, number, number]`,
            // fallthrough from `case 0` is unreachable, so `x.length` is `2 | 3`
            const _: 2 | 3 = x.length
        }
    }
}
```

## Behavior with `typescript@6.0`

`typescript@6.0.3`: compiles without errors.

## Behavior with `tsgo`

`typescript@7.0.2` (also `@typescript/native-preview` `7.0.0-dev.20260707.2`):

```
error TS2322: Type '1 | 2 | 3' is not assignable to type '2 | 3'.
  Type '1' is not assignable to type '2 | 3'.
```

tsgo treats the fallthrough edge from `case 0` into `case 1` as reachable and carries the un-narrowed `x` (lengths `1 | 2`) across it, even though the inner switch is exhaustive.

## Notes

tsgo appears to know the end of `case 0` is unreachable in other contexts — this variant compiles cleanly on 7.0.2, accepting `x: never` after the inner switch:

```ts
        case 0: {
            switch (x.length) {
                case 1: case 2: return undefined
            }
            const probe: never = x  // OK on tsgo 7.0.2
            return undefined
        }
```

The bug seems to need the inner switch's exhaustiveness to depend on `x` being co-narrowed by the outer switch on the destructured discriminant `i`. These variants do NOT reproduce (both compilers accept them):

- inner switch on a plain string union (`'a' | 'b'`) instead of tuple `.length`;
- inner switch on the `.length` of a separate parameter `x: readonly [number] | readonly [number, number]` whose type doesn't depend on `i`.

**Workaround:** add `throw 'unreachable'` at the end of `case 0` after the inner switch.

### PR DESCRIPTION
**Pull request by Andarist**
fixes https://github.com/microsoft/typescript-go/issues/4572
fixes https://github.com/microsoft/typescript-go/issues/4613

### CODE REVIEW

File: internal/checker/checker.go [hunk 1]
```diff
@@ -13692,6 +13699,8 @@ func (c *Checker) getNarrowedTypeOfSymbol(symbol *ast.Symbol, location *ast.Node
 					if parentType != nil {
 						parentTypeConstraint = c.mapType(parentType, c.getBaseConstraintOrType)
 					}
+					// Guard parent-type resolution only; flow analysis should allow re-entrant narrowing
+					links.flags &^= NodeCheckFlagsInCheckIdentifier
```
Comment (Andarist) [inline internal/checker/checker.go:13723]: https://github.com/microsoft/typescript-go/pull/2542 pushed this to the latter line - and that's what broke the reported case

But now, thanks to the introduced `rootInitializer` check, we just never enter this entire branch. It seems to me that thanks to that we can push back this flag reset to an earlier spot (that is required to fix one of the tests I added as part of this PR)

**Review by ahejlsberg — APPROVED** [review]

**Review by RyanCavanaugh — APPROVED** [review]
