### ISSUE TITLE
importsNotUsedAsValues is not implemented yet.

### ISSUE THREAD

**Issue by Raynos** [microsoft/typescript-go#1683]
## Steps to reproduce

I use a tsconfig with

{ 
   ...
   "importsNotUsedAsValues": "remove",
} 

## Behavior with `typescript@5.8`

Build succeeds.

## Behavior with `tsgo`

```
[04:31:59 PM] Building project 'workspaces/mini-services/tsconfig.json'...

tsconfig/tsconfig.base.json:24:5 - error TS5023: Unknown compiler option 'importsNotUsedAsValues'.

24     "importsNotUsedAsValues": "remove",
       ~~~~~~~~~~~~~~~~~~~~~~~~
```

I do see that the tsconfig handbook says this option is deprecated. It could be useful to say in the tsgo error whether it's an "Unknown compiler option" vs either an "Not yet implemented option '...'" or "deprecated option which will not be implemented '...'"

**Comment by jakebailey** [comment]
What version of TS were you using? You've had to silence a deprecation since 5.0 (2+ years ago), and then it entirely stopped working in 5.5, which was more than a year ago.

I don't think we're intending on giving even _more_ notice here...

**Comment by jakebailey** [comment]
In any case, we're not going to do this.

**Comment by Raynos** [comment]
```
$ NODE_OPTIONS="--max-old-space-size=6144" tsc --version
Version 5.8.3
```

There was no warning in 5.8.3 complaining about this flag, but i did port away from the deprecated option. Would be nice if either tsc or tsgo said that the flag is permanently removed instead of not known. Would be less confusing

**Comment by jakebailey** [comment]
That is certainly strange, but I also see that. It's supposed to error: https://github.com/microsoft/TypeScript/blob/0f4b3387bda8500889d398d65dddcfeb352f3774/src/compiler/program.ts#L4521

**Comment by jakebailey** [comment]
Ugh, the deprecation code was incorrectly using a truthy check instead of `!== undefined`. `Remove` is `0` internally.

**Comment by jakebailey** [comment]
Actually, the default is `Remove`, which means you can simply delete the option and we will do the same thing. So the option is getting removed, we just never errored on the one setting that was okay. You should be fine to delete it from both and it work fine.

**Comment by Raynos** [comment]
Thanks jake that's really helpful context.

**Comment by Raynos** [comment]
I did run tsgo on our monorepo and I can try and export a bunch of edgecases into issues here if that's helpful, but seeing that its a private company monorepo making actual minimal reproductions is something time consuming I dont have time for, 

But happy to verbally list a bunch of edgecases between tsc & tsgo nightly
