### ISSUE TITLE
Regression in 20260613.1 pertaining to conditional types

### ISSUE THREAD

**Issue by ashvinsrivatsa** [microsoft/typescript-go#4463]
## Steps to reproduce

https://github.com/ashvinsrivatsa/tsgo-jsts-regression

```
$ ./test.sh
tsc 6.0.3                 -> 0
tsgo 7.0.0-dev.20260612.1 -> 0
byhand/repro.ts:72:21 - error TS2344: Type 'MergeSubSchema<SUB_SCHEMAS_HEAD, RemoveInvalidAdditionalProperties<RemoveInvalidAdditionalItems<SUB_SCHEMAS_HEAD>>>' does not satisfy the constraint 'JSONSchema'.
  Type 'MergeSubSchema<SUB_SCHEMAS_HEAD, RemoveInvalidAdditionalProperties<RemoveInvalidAdditionalItems<SUB_SCHEMAS_HEAD>>>' has no properties in common with type 'Readonly<{ items?: JSONSchema | undefined; additionalItems?: JSONSchema | undefined; properties?: JSONSchema | undefined; additionalProperties?: JSONSchema | undefined; }>'.

72       ? ParseSchema<MergeSubSchema<SUB_SCHEMAS_HEAD>>
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in byhand/repro.ts:72

tsgo 7.0.0-dev.20260613.1 -> 1
byhand/repro.ts:72:21 - error TS2344: Type 'MergeSubSchema<SUB_SCHEMAS_HEAD, RemoveInvalidAdditionalProperties<RemoveInvalidAdditionalItems<SUB_SCHEMAS_HEAD>>>' does not satisfy the constraint 'JSONSchema'.
  Type 'MergeSubSchema<SUB_SCHEMAS_HEAD, RemoveInvalidAdditionalProperties<RemoveInvalidAdditionalItems<SUB_SCHEMAS_HEAD>>>' has no properties in common with type 'Readonly<{ items?: JSONSchema | undefined; additionalItems?: JSONSchema | undefined; properties?: JSONSchema | undefined; additionalProperties?: JSONSchema | undefined; }>'.

72       ? ParseSchema<MergeSubSchema<SUB_SCHEMAS_HEAD>>
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in byhand/repro.ts:72

tsgo 7.0.0-dev.20260627.2 -> 1
```

Claude bisected this to #4242.

I encountered this in a private codebase that has a transitive dependency on [json-schema-to-ts@3.1.1](https://www.npmjs.com/package/json-schema-to-ts/v/3.1.1); `byhand/repro.ts` in the above-linked repo is a reduced form of the problematic code.

## Behavior with `typescript@6.0`

The code compiles with no error.

## Behavior with `tsgo`

In @typescript/native-preview@7.0.0-dev.20260613.1 and higher, a TS2344 error is issued by the compiler:

```
error TS2344: Type 'MergeSubSchema<SUB_SCHEMAS_HEAD, RemoveInvalidAdditionalProperties<RemoveInvalidAdditionalItems<SUB_SCHEMAS_HEAD>>>' does not satisfy the constraint 'JSONSchema'.
  Type 'MergeSubSchema<SUB_SCHEMAS_HEAD, RemoveInvalidAdditionalProperties<RemoveInvalidAdditionalItems<SUB_SCHEMAS_HEAD>>>' has no properties in common with type 'Readonly<{ items?: JSONSchema | undefined; additionalItems?: JSONSchema | undefined; properties?: JSONSchema | undefined; additionalProperties?: JSONSchema | undefined; }>'.
```

**Comment by jakebailey** [comment]
Bisects to #4242 @ahejlsberg

**Comment by jakebailey** [comment]
Oh doh, that was already in the issue
