### ISSUE TITLE
`unique symbol` is now lost when accessed through a property

### ISSUE THREAD

**Issue by arcanis** [microsoft/typescript-go#1682]
## Steps to reproduce

```typescript
function foo() {}

const mySymbol = Symbol();
foo.sym = mySymbol;

const shouldWork: typeof mySymbol = foo.sym;
```

## Behavior with `typescript@5.8`

Works in 5.8 / 5.9:

https://www.typescriptlang.org/play/?#code/GYVwdgxgLglg9mABMOcAUBKRBvAvgKHwgQGcpEBbATwGUqKAjOAG0QF5E7GXMBufFHAB0Jeu0q16TZvyKlyJABZwQzACYB1OACcA1gC5EUKgAcApnGASu08YJH1+QA

## Behavior with `tsgo`

```
main.ts(6,7): error TS2322: Type 'symbol' is not assignable to type 'unique symbol'.
```

Weirdly the hover properly returns `typeof mySymbol` when hovering `sym`, but tsgo is still unhappy.

**Comment by ahejlsberg** [comment]
I'm actually surprised at the Strada behavior. Consider:

```ts
const mySymbol = Symbol();
let sym = mySymbol; // Widened to type symbol

const shouldWork: typeof mySymbol = sym; // Error
```

The above is an error with both Strada and Corsa because we widen the `unique symbol` type when inferring from an initializer for a mutable location. Since the `foo.sym` expando property is indeed a mutable location, I'd expect widening (and thus the follow-on error) to occur in the original example, as it does with the new compiler. So, I think this is actually a bug/inconsistency in the old compiler.
