### ISSUE TITLE
Exhaustive switch on co-narrowed tuple's `.length` does not terminate fallthrough control flow (works in TS 6.0)

### ISSUE THREAD

**Issue by sergey-shandar** [microsoft/typescript-go#4613]
## Steps to reproduce

Compile the following with `tsc --strict --noEmit` (no other options needed; also reproduces with default options):

```ts
type F =
    | readonly [0, readonly [number]]
    | readonly [0 | 1, readonly [number, number]]
    | readonly [1, readonly [number, number, number]]

const f = ([i, x]: F): undefined => {
    switch (i) {
        case 0: {
            // `x` is narrowed to `readonly [number] | readonly [number, number]`,
            // so `x.length` is `1 | 2` and this inner switch is exhaustive;
            // the end of `case 0` is therefore unreachable:
            switch (x.length) {
                case 1: case 2: return undefined
            }
        }
        case 1: {
            // direct entry: `x` is `readonly [number, number] | readonly [number, number, number]`,
            // fallthrough from `case 0` is unreachable, so `x.length` is `2 | 3`
            const _: 2 | 3 = x.length
        }
    }
}
```

## Behavior with `typescript@6.0`

`typescript@6.0.3`: compiles without errors.

## Behavior with `tsgo`

`typescript@7.0.2` (also `@typescript/native-preview` `7.0.0-dev.20260707.2`):

```
error TS2322: Type '1 | 2 | 3' is not assignable to type '2 | 3'.
  Type '1' is not assignable to type '2 | 3'.
```

tsgo treats the fallthrough edge from `case 0` into `case 1` as reachable and carries the un-narrowed `x` (lengths `1 | 2`) across it, even though the inner switch is exhaustive.

## Notes

tsgo appears to know the end of `case 0` is unreachable in other contexts — this variant compiles cleanly on 7.0.2, accepting `x: never` after the inner switch:

```ts
        case 0: {
            switch (x.length) {
                case 1: case 2: return undefined
            }
            const probe: never = x  // OK on tsgo 7.0.2
            return undefined
        }
```

The bug seems to need the inner switch's exhaustiveness to depend on `x` being co-narrowed by the outer switch on the destructured discriminant `i`. These variants do NOT reproduce (both compilers accept them):

- inner switch on a plain string union (`'a' | 'b'`) instead of tuple `.length`;
- inner switch on the `.length` of a separate parameter `x: readonly [number] | readonly [number, number]` whose type doesn't depend on `i`.

**Workaround:** add `throw 'unreachable'` at the end of `case 0` after the inner switch.
