### ISSUE TITLE
Behavior difference: callback contextual typing — `tsc@5.9.3` passes, `tsc@6.0.3` / `tsgo` fail

### ISSUE THREAD

**Issue by dougludlow** [microsoft/typescript-go#3788]
**TL;DR:** On the same source and same `pnpm` install, `typescript@6.0.3` and `tsgo` emit `TS7006` / `TS7031` on callback parameters that `typescript@5.9.3` types correctly. The condition that surfaces it is pnpm's `enableGlobalVirtualStore` symlink layout — which `tsc@5.9.3`, Node, and bundlers all handle without issue.

## Steps to reproduce

Repro repo (single file, single tsconfig): https://github.com/dougludlow/ts-callback-inference-bug

```tsx
import type { Meta, StoryObj } from '@storybook/react-vite';
import type { ElementType, ReactNode } from 'react';

interface LabelProps { id: string; children: ReactNode; }
interface WidgetProps { metric: number; slots?: { label?: ElementType<LabelProps> }; }

declare function Widget(props: WidgetProps): ReactNode;

type Story = StoryObj<typeof Widget>;
const meta: Meta<typeof Widget> = { component: Widget };
export default meta;

export const CustomLabel: Story = {
	args: {
		metric: 50,
		slots: {
			label: ({ id, children }) => <span id={id}>{children}</span>,
		},
	},
};
```

Bare `tsconfig.json` (no `strict`, no `noImplicitAny`). `pnpm-workspace.yaml` contains `enableGlobalVirtualStore: true`. Commenting that line out makes all three compilers pass on the same source.

## Behavior with `typescript@5.9.3`

Passes.

## Behavior with `typescript@6.0.3`

```
repro.tsx(29,14): error TS7031: Binding element 'id' implicitly has an 'any' type.
repro.tsx(29,18): error TS7031: Binding element 'children' implicitly has an 'any' type.
```

## Behavior with `tsgo` (`@typescript/native-preview@7.0.0-dev.20260509.2`)

Same `TS7031` errors as `typescript@6.0.3`.

## Additional context

The repro is the smallest shape I could isolate; in real code the same failure pattern surfaces in Storybook story args, `material-react-table` cell/header callbacks, Vitest `it.each` destructuring, MUI event handlers, and Express middleware — anywhere a callback's contextual type comes through a generic from a third-party `.d.ts`.

`preserveSymlinks: true` is not a fix. The only workaround we've found is annotating each callsite (`({ id, children }: LabelProps)`).

Pnpm-side report of the same trigger: https://github.com/pnpm/pnpm/issues/9739.

**Comment by Andarist** [comment]
It would be great if you could pull all of the relevant 3rd party types into a single file - a good repro usually can be created in a single import-less TS playground.

**Comment by dougludlow** [comment]
@Andarist I’m not sure I follow, the problem has to do specifically with imports when using pnpm’s `enableGlobalVirtualStore’ feature. It works fine in typescript v5.9.3, but not in later versions (v6/v7).

**Comment by Andarist** [comment]
Ah, I'm sorry! I've missed that this specifically requires `enableGlobalVirtualStore`

**Comment by Andarist** [comment]
I don't see this actually working with TS 5.9 in the way you claimed. It does not error in TS 5.9, but simply because the default `noImplicitAny: false` (and the default was changed [here](https://github.com/microsoft/TypeScript/pull/63087)). However, it does not actually provide contextual typing for that related parameter. You can verify that in the IDE:

<img width="865" height="430" alt="Image" src="https://github.com/user-attachments/assets/eb7f434f-7a7c-4bc4-bfcf-9d8b70f9e4ee" />

To learn what happens under the hood here, it's useful to run this with `--traceResolution`. I think the most insightful part is this:

<details>
<summary>======== Resolving module 'react' from '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/@storybook/react/dist/index.d.ts'. ========</summary>

```
Explicitly specified module resolution kind: 'Bundler'.
Resolving in CJS mode with conditions 'import', 'types'.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/@storybook/react/dist/package.json' does not exist according to earlier cached lookups.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/@storybook/react/package.json' exists according to earlier cached lookups.
Loading module 'react' from 'node_modules' folder, target file types: TypeScript, JavaScript, Declaration, JSON.
Searching all ancestor node_modules directories for preferred extensions: TypeScript, Declaration.
Directory '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/@storybook/react/dist/node_modules' does not exist, skipping all lookups in it.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/@storybook/react/node_modules/react.ts' does not exist.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/@storybook/react/node_modules/react.tsx' does not exist.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/@storybook/react/node_modules/react.d.ts' does not exist.
Directory '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/@storybook/react/node_modules/@types' does not exist, skipping all lookups in it.
Directory '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/@storybook/node_modules' does not exist, skipping all lookups in it.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react/package.json' exists according to earlier cached lookups.
Entering conditional exports.
Saw non-matching condition 'react-server'.
Matched 'exports' condition 'default'.
Using 'exports' subpath '.' with target './index.js'.
File name '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react/index.js' has a '.js' extension - stripping it.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react/index.ts' does not exist.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react/index.tsx' does not exist.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react/index.d.ts' does not exist.
Failed to resolve under condition 'default'.
Exiting conditional exports.
Directory '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/@types' does not exist, skipping all lookups in it.
Directory '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/node_modules' does not exist, skipping all lookups in it.
Directory '/Library/pnpm/store/v11/links/@storybook/react/node_modules' does not exist, skipping all lookups in it.
Directory '/Library/pnpm/store/v11/links/@storybook/node_modules' does not exist, skipping all lookups in it.
Directory '/Library/pnpm/store/v11/links/node_modules' does not exist, skipping all lookups in it.
Directory '/Library/pnpm/store/v11/node_modules' does not exist, skipping all lookups in it.
Directory '/Library/pnpm/store/node_modules' does not exist, skipping all lookups in it.
Directory '/Library/pnpm/node_modules' does not exist, skipping all lookups in it.
Directory '/Library/node_modules' does not exist, skipping all lookups in it.
Directory '/node_modules' does not exist, skipping all lookups in it.
Directory '/Users/node_modules' does not exist, skipping all lookups in it.
Directory '/node_modules' does not exist, skipping all lookups in it.
Searching all ancestor node_modules directories for fallback extensions: JavaScript, JSON.
Directory '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/@storybook/react/dist/node_modules' does not exist, skipping all lookups in it.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/@storybook/react/node_modules/react.js' does not exist.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/@storybook/react/node_modules/react.jsx' does not exist.
Directory '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/@storybook/node_modules' does not exist, skipping all lookups in it.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react/package.json' exists according to earlier cached lookups.
Entering conditional exports.
Saw non-matching condition 'react-server'.
Matched 'exports' condition 'default'.
Using 'exports' subpath '.' with target './index.js'.
File name '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react/index.js' has a '.js' extension - stripping it.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react/index.js' exists - use it as a name resolution result.
'package.json' does not have a 'peerDependencies' field.
Resolved under condition 'default'.
Exiting conditional exports.
Resolution of non-relative name failed; trying with modern Node resolution features disabled to see if npm library needs configuration update.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/@storybook/react/dist/package.json' does not exist according to earlier cached lookups.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/@storybook/react/package.json' exists according to earlier cached lookups.
Loading module 'react' from 'node_modules' folder, target file types: TypeScript, Declaration.
Searching all ancestor node_modules directories for preferred extensions: TypeScript, Declaration.
Directory '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/@storybook/react/dist/node_modules' does not exist, skipping all lookups in it.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/@storybook/react/node_modules/react.ts' does not exist.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/@storybook/react/node_modules/react.tsx' does not exist.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/@storybook/react/node_modules/react.d.ts' does not exist.
Directory '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/@storybook/react/node_modules/@types' does not exist, skipping all lookups in it.
Directory '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/@storybook/node_modules' does not exist, skipping all lookups in it.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react/package.json' exists according to earlier cached lookups.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react.ts' does not exist.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react.tsx' does not exist.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react.d.ts' does not exist.
'package.json' does not have a 'typesVersions' field.
'package.json' does not have a 'typings' field.
'package.json' does not have a 'types' field.
'package.json' has 'main' field 'index.js' that references '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react/index.js'.
File name '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react/index.js' has a '.js' extension - stripping it.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react/index.ts' does not exist.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react/index.tsx' does not exist.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react/index.d.ts' does not exist.
Loading module as file / folder, candidate module location '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react/index.js', target file types: TypeScript, Declaration.
File name '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react/index.js' has a '.js' extension - stripping it.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react/index.ts' does not exist.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react/index.tsx' does not exist.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react/index.d.ts' does not exist.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react/index.js.ts' does not exist.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react/index.js.tsx' does not exist.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react/index.js.d.ts' does not exist.
Directory '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react/index.js' does not exist, skipping all lookups in it.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react/index.ts' does not exist.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react/index.tsx' does not exist.
File '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react/index.d.ts' does not exist.
Directory '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/@types' does not exist, skipping all lookups in it.
Directory '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/node_modules' does not exist, skipping all lookups in it.
Directory '/Library/pnpm/store/v11/links/@storybook/react/node_modules' does not exist, skipping all lookups in it.
Directory '/Library/pnpm/store/v11/links/@storybook/node_modules' does not exist, skipping all lookups in it.
Directory '/Library/pnpm/store/v11/links/node_modules' does not exist, skipping all lookups in it.
Directory '/Library/pnpm/store/v11/node_modules' does not exist, skipping all lookups in it.
Directory '/Library/pnpm/store/node_modules' does not exist, skipping all lookups in it.
Directory '/Library/pnpm/node_modules' does not exist, skipping all lookups in it.
Directory '/Library/node_modules' does not exist, skipping all lookups in it.
Directory '/node_modules' does not exist, skipping all lookups in it.
Directory '/Users/node_modules' does not exist, skipping all lookups in it.
Directory '/node_modules' does not exist, skipping all lookups in it.
Resolving real path for '/Library/pnpm/store/v11/links/@storybook/react/10.3.6/da6a349faeea73257b829ab151821481104c7c3d50e60b07bbb240ce61abb7f7/node_modules/react/index.js', result '/Library/pnpm/store/v11/links/@/react/19.2.6/0683447262373d5c07e3b5303143da00a9490331f3f74e42c53dc947c04af8ea/node_modules/react/index.js'.
======== Module name 'react' was successfully resolved to '/Library/pnpm/store/v11/links/@/react/19.2.6/0683447262373d5c07e3b5303143da00a9490331f3f74e42c53dc947c04af8ea/node_modules/react/index.js' with Package ID 'react/index.js@19.2.6'. ========
```
</details>

We  can see at the bottom of the above log that it ended up resolving to the React's JS file - and not to `@types/react` package.

This really looks to me like an issue with `@storybook/react@10.3.6` (that was already fixed in [this PR](https://github.com/storybookjs/storybook/pull/34641)), you can work around it in your project with:
```yml
packageExtensions:
  '@storybook/react@10.3.6':
    peerDependenciesMeta:
      '@types/react':
        optional: true
```

**Comment by dougludlow** [comment]
Oh man! 🤦 Ok, thanks for digging into this and thanks for the `--traceResolution` hint. I forgot that v6/7 introduce very different defaults. I have several such cases in one of my projects, but I predict most of them are incorrectly configured peer dependencies. Thanks so much for your time!
