### PR TITLE
Add conditional type base constraint limiter

### LINKED ISSUE #4391: const type parameter doesn't capture string-literal property when the parameter type is wrapped in Omit<...>
Note: I used Claude to troubleshoot and craft the repro and description.  

## Steps to reproduce

A `const` type parameter on an interface call signature stops capturing a string-literal property from the argument object **when the parameter's type is wrapped in a homomorphic mapped type (`Omit<...>`)**. The literal widens to `string`, collapsing a downstream conditional type and producing a spurious `TS2353`.

Minimal repro (depends on TanStack Router, which uses this pattern for its route-bound `Route.redirect`, whose options type is `Omit<RedirectOptions<…>, 'from'>`): https://github.com/IanVS/tsgo-error-repro

`repro.ts`
```ts
import { createRootRoute, createRoute, createRouter, redirect } from "@tanstack/react-router";

const rootRoute = createRootRoute();
const agentRoute = createRoute({ getParentRoute: () => rootRoute, path: "/agents/$agentName" });
const agentIndexRoute = createRoute({ getParentRoute: () => agentRoute, path: "/" });
const sessionRoute = createRoute({ getParentRoute: () => agentRoute, path: "/$sessionId" });
const routeTree = rootRoute.addChildren([agentRoute.addChildren([agentIndexRoute, sessionRoute])]);
const router = createRouter({ routeTree });
declare module "@tanstack/react-router" {
  interface Register { router: typeof router; }
}

// A) plain redirect, no `from` — OK on both compilers
redirect({
  to: "/agents/$agentName/$sessionId",
  params: { agentName: "a", sessionId: "s" },
});

// B) plain redirect WITH explicit `from` (options NOT Omit-wrapped) — OK on both compilers
redirect({
  from: "/agents/$agentName/",
  to: "/agents/$agentName/$sessionId",
  params: { agentName: "a", sessionId: "s" },
});

// C) route-bound redirect — options type is Omit<RedirectOptions<…>, "from">
agentIndexRoute.redirect({
  to: "/agents/$agentName/$sessionId",
  params: { agentName: "a", sessionId: "s" },
});
```

All three calls are valid: `sessionId` is a real path param of `/agents/$agentName/$sessionId`, supplied correctly. The only difference between case **B** (accepted everywhere) and case **C** (rejected by tsgo) is that C's options parameter is typed `Omit<RedirectOptions<…>, 'from'>` instead of an unwrapped object — isolating the mapped-type wrapper as the trigger.

The relevant declaration in `@tanstack/router-core`:
```ts
interface RedirectFnRoute<in out TDefaultFrom extends string = string> {
  <TRouter extends AnyRouter, const TTo extends string | undefined = undefined, ...>(
    opts: Omit<RedirectOptions<TRouter, TDefaultFrom, TTo, ...>, 'from'>   // <-- mapped type
  ): Redirect<...>;
}
```

## Behavior with `typescript@6.0`

No errors (verified with `typescript@6.0.3`). All three calls type-check.

## Behavior with `tsgo`

Case **C** is rejected:

```
repro.ts(31,29): error TS2353: Object literal may only specify known properties, and 'sessionId'
does not exist in type 'ParamsReducerFn<RouterCore<…>, ...> | { ... }'.
```

The `to`-dependent type parameter resolves as `string` rather than the literal `"/agents/$agentName/$sessionId"`, so the params type collapses to the parent route's params (`{ agentName }`) and `sessionId` is rejected.

Regression bisect (`@typescript/native-preview`):

| Build | Result |
| --- | --- |
| `7.0.0-dev.20260612.1` | OK |
| `7.0.0-dev.20260613.1` | **TS2353 (first bad build)** |
| `7.0.0-dev.20260617.2` | TS2353 |
| `7.0.0-dev.20260622.1` | TS2353 (latest) |

### LINKED ISSUE #4463: Regression in 20260613.1 pertaining to conditional types
## Steps to reproduce

https://github.com/ashvinsrivatsa/tsgo-jsts-regression

```
$ ./test.sh
tsc 6.0.3                 -> 0
tsgo 7.0.0-dev.20260612.1 -> 0
byhand/repro.ts:72:21 - error TS2344: Type 'MergeSubSchema<SUB_SCHEMAS_HEAD, RemoveInvalidAdditionalProperties<RemoveInvalidAdditionalItems<SUB_SCHEMAS_HEAD>>>' does not satisfy the constraint 'JSONSchema'.
  Type 'MergeSubSchema<SUB_SCHEMAS_HEAD, RemoveInvalidAdditionalProperties<RemoveInvalidAdditionalItems<SUB_SCHEMAS_HEAD>>>' has no properties in common with type 'Readonly<{ items?: JSONSchema | undefined; additionalItems?: JSONSchema | undefined; properties?: JSONSchema | undefined; additionalProperties?: JSONSchema | undefined; }>'.

72       ? ParseSchema<MergeSubSchema<SUB_SCHEMAS_HEAD>>
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in byhand/repro.ts:72

tsgo 7.0.0-dev.20260613.1 -> 1
byhand/repro.ts:72:21 - error TS2344: Type 'MergeSubSchema<SUB_SCHEMAS_HEAD, RemoveInvalidAdditionalProperties<RemoveInvalidAdditionalItems<SUB_SCHEMAS_HEAD>>>' does not satisfy the constraint 'JSONSchema'.
  Type 'MergeSubSchema<SUB_SCHEMAS_HEAD, RemoveInvalidAdditionalProperties<RemoveInvalidAdditionalItems<SUB_SCHEMAS_HEAD>>>' has no properties in common with type 'Readonly<{ items?: JSONSchema | undefined; additionalItems?: JSONSchema | undefined; properties?: JSONSchema | undefined; additionalProperties?: JSONSchema | undefined; }>'.

72       ? ParseSchema<MergeSubSchema<SUB_SCHEMAS_HEAD>>
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in byhand/repro.ts:72

tsgo 7.0.0-dev.20260627.2 -> 1
```

Claude bisected this to #4242.

I encountered this in a private codebase that has a transitive dependency on [json-schema-to-ts@3.1.1](https://www.npmjs.com/package/json-schema-to-ts/v/3.1.1); `byhand/repro.ts` in the above-linked repo is a reduced form of the problematic code.

## Behavior with `typescript@6.0`

The code compiles with no error.

## Behavior with `tsgo`

In @typescript/native-preview@7.0.0-dev.20260613.1 and higher, a TS2344 error is issued by the compiler:

```
error TS2344: Type 'MergeSubSchema<SUB_SCHEMAS_HEAD, RemoveInvalidAdditionalProperties<RemoveInvalidAdditionalItems<SUB_SCHEMAS_HEAD>>>' does not satisfy the constraint 'JSONSchema'.
  Type 'MergeSubSchema<SUB_SCHEMAS_HEAD, RemoveInvalidAdditionalProperties<RemoveInvalidAdditionalItems<SUB_SCHEMAS_HEAD>>>' has no properties in common with type 'Readonly<{ items?: JSONSchema | undefined; additionalItems?: JSONSchema | undefined; properties?: JSONSchema | undefined; additionalProperties?: JSONSchema | undefined; }>'.
```

### LINKED ISSUE #63568: Regression: 7.0.1-RC Unable to Satisfy Recursive Mapped Type Constraint
### 🔎 Search Terms

Mapped Types, Satisfying Constraints, Recursive Type Mapping, TypeScript 7, RC

### 🕗 Version & Regression Information

> This changed between versions 

Between `6.0.3` and `7.0.1-rc`

> This changed in commit or PR  

Unknown. However I recall things were working ok approximately 2 weeks ago. The update may be recent.

- This is the behavior in every version I tried

Tested `4.9.5` through to `6.0.3`. Problem is specific to `7.0.1-rc`

### ⏯ Playground Link

https://www.typescriptlang.org/play/?target=99&module=7&ts=4.9.5#code/JYWwDg9gTgLgBALzgMyhEcDkCIBNMBQBA9MXALSVXU2130ONMlkCSAdqgIYDOMUAVwDGMAVACmLCkxmy58ouIAekWHBgBPMOLgAVAMpCAFuJBc4AXjgBvdVvEAuOHyjB2AczgBfRSujxNbT0AeTAYYAh2LgAbAB5dezhlGHF2XB49QxMzS0zjUy4APlyEoIAyGywAPwgwiKjozCd+AR0fAmVVeDcUqGQuIR1dACVxZFjR5CSlFLSMlzd3YuTU9Lzs81sCODttJ0xJzAAaOG24CWQnSdOfTv84HvE+gaH9fkXp2bWDfJytncCjiwb1cHkwN18XV2QwACmhtLBgOIMlZRkJoLhYnDak9NABpcQaE4-DaFSH3R7PQYhABGACtxCIsfDcUiMis5npsQjwsjljNVhkSQUbGdAftgvTGTBCDswCzEcinNzWciCO1SNJ5NqddqpABZLhgMCLKS680WhgEQFwABaeFKOisCAAdOiJC79OhxI6iDbdAAxNAgSaxADCkRSM0+gq5Ct5PBO1w5awWHmKVgAFGdkwLOQBrQkQKYR9hRmBnHYAfj0QfQjvDkeSJ1L5YA2pMALpknY7Jyu+24ABy4gAbk8CABKa2JQPBlWwDSNsvJGOc3QLhPExIpoVZApHM4AdWAMCMjrXa0HF6sc-r9mX5e32kKh52J7PoXCkRil4y18SW8dzzb4v3qX8awHPAwJ-OIP3PexiiceDHUPDM4HgmCGj9Wc6xASUGSZVtV13OMcUVRM4E3Nk-zInk2TfOBNUNY1xFwPRElGdwJB4Hh6jgAAJJ5JB2Ugzk1YJ8ycHYADYXQABhdABmcSyADLhgGiJwAHYFJdABGcgoCEVTVLgABRKA0CgJwL0wWw2wJDQHnYOBCw0YsqPjNlO2VbzkUcwlO1osyQjqWD4n3MxihrQcsJieI8IbYiZhOaiAqc7tijgF1ctynNkQEaJ4FIgCgmdF04qlJlrErOBAuctw3KLKZ0p4Xza3neMlxSmA0v8ngGu7M4vDJdDRh4IqKxnII7xAEEPgqwcFo8HDZqSh9etojcBufHRSOFaLcmzHYLwOgjpViNxkCeLzyITba2pizr0Auoim1Su76L5OAHDOM6QKFUNrtu3Mvnmd50zgGs5tDXqkzGJD-uA8HMkhzwYbwlbPD+nYoOHMcJ2nM1LVJ0mpAAVR4Lh3EkTUyYZ801p0DgwAEeBbzemBYlqnYlFs0NMAAQUwV8zg0AWxliYXRcYhBJfGGWyVGmadGCdm2Y5l6QAbWxe01G11ZgTXcnxrmebOIXbOx3tbbtu3NT5-tKrwbGAG51ROVn2ey+2-YdsgdglxAXdwd26v9yP-cdxBneW9GPajpPo7ILwTldd1xBdAASBYwDJIA

### 💻 Code

The following code will fault on` 7.0.1-rc`

The issue relates to the `TFromObject` mapping where it's not possible to satisfy the left side `ZodType` constraint. The issue is specific to resolving a foreign `TRef<T>` on a remote `Context` object.

```ts
import z from 'zod'

// ------------------------------------------------------------------
// Infrastructure
// ------------------------------------------------------------------

export type TSchema = { type: string }

export type TOptional<Type extends TSchema = TSchema> = Type & { '~optional': true }

export interface TRef<Ref extends string> extends TSchema { 
  type: 'Ref', 
  ref: Ref 
}
export interface TString extends TSchema { 
  type: 'String' 
}

export type TProperties = Record<PropertyKey, TSchema>

export interface TObject<Properties extends TProperties> extends TSchema {
  type: 'Object'
  properties: Properties
}

// ------------------------------------------------------------------
// Mapping
// ------------------------------------------------------------------
type ZodType = z.core.SomeType

type TFromRef<Context extends TProperties, Ref extends string> = (
  Ref extends keyof Context
    ? TFromType<Context, Context[Ref]>
    : z.ZodNever
)
type TFromProperty<Context extends TProperties, Type extends TSchema,
  WithType extends ZodType = TFromType<Context, Type>,
  WithOptional extends ZodType = Type extends TOptional ? z.ZodOptional<WithType> : WithType,
> = WithOptional

type TFromObject<Context extends TProperties, Properties extends TProperties,
  // Mapped Type Regression Here
  //
  // Ok:   6.0.3
  // Fail: 7.0.1-rc
  //
  // Error: Type '{ [Key in keyof Properties]: Properties[Key] extends 
  //  TOptional<TSchema> ? ZodOptional<TFromType<Context, Properties[Key]>>  .....
  Result extends ZodType = z.ZodObject<{
    [Key in keyof Properties]: TFromProperty<Context, Properties[Key]>
  }>
> = Result

type TFromString = z.ZodString

type TFromType<Context extends TProperties, Type extends TSchema> = (
  Type extends TObject<infer Properties extends TProperties> ? TFromObject<Context, Properties> :
  Type extends TRef<infer Ref extends string> ? TFromRef<Context, Ref> :
  Type extends TString ? TFromString :
  z.ZodNever
)

// ------------------------------------------------------------------
// Usage
// ------------------------------------------------------------------

type Input = TObject<{
  x: TRef<'A'>,
  y: TRef<'A'>,
  z: TRef<'A'>
}>
type Output = TFromType<{    // type Output = z.ZodObject<{
  A: TString                 //   x: z.ZodString;
}, Input>                    //   y: z.ZodString;
                             //   z: z.ZodString;
                             // }, z.core.$strip>


```

### 🙁 Actual behavior

Expected similar behavior to TypeScript 6

### 🙂 Expected behavior

Expected similar behavior to TypeScript 6

### Additional information about the issue

I note that by commenting the conditional `TRef<T>` arm on `TFromType<T>` will make the problem disappear. So the issue appears specific to how TypeScript 7 is resolving for the foreign type. Previous versions of the compiler did seem to collapse to the target type, where as TypeScript 7 seems to keep the type expansive.

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR reverts #4242 (but keeps the tests) and instead provides a simple base constraint limiter that stops exploring distributive conditional type constraints at a depth of 100.

Fixes #4391.
Fixes #4463.
Fixes https://github.com/microsoft/TypeScript/issues/63568.

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot test it

**Review by jakebailey — APPROVED** [review]
Sort of funny to end up here given this is what copilot said to do before 😄

**Comment by ahejlsberg** [comment]
> Sort of funny to end up here given this is what copilot said to do before

Must have missed that, I don't see it suggesting this solution anywhere. I'm still not 100% in love with it, but it is similar in nature to the instantiation and relation depth limiters and gets the job done with no changes in semantics.

**Comment by jakebailey** [comment]
I am unfortunately confusing it for one of the other many PRs copilot has opened to add a limiter
