### ISSUE TITLE
Type inference broken with angular inject function + @ngrx/store

### ISSUE THREAD

**Issue by mattlewis92** [microsoft/typescript-go#1222]
Minimal repro (that compiles with typescript 5.8)

```
import {inject} from '@angular/core';
import {Store} from '@ngrx/store';

const store: Store = inject(Store);
```

Output with tsgo:
```
store-generic-inference/index.ts:4:7 - error TS2322: Type 'Store<unknown>' is not assignable to type 'Store<object>'.
  Type 'unknown' is not assignable to type 'object'.

4 const store: Store = inject(Store);
        ~~~~~

Found 1 error in store-generic-inference/index.ts:4
```

Minimal repro can be run here: https://github.com/mattlewis92/ts-go-issues-repros

**Comment by mattlewis92** [comment]
Standalone example with no dependencies:
```typescript
class Store<T = object> {
    select<K>(mapFn: (state: T) => K) {};
}

const store: Store = inject(Store);

function inject<T>(token: ProviderToken<T>): T {
    return {} as T;
}

interface Type<T> extends Function {
    new (...args: any[]): T;
}

type ProviderToken<T> = Type<T> | AbstractType<T>;

interface AbstractType<T> extends Function {
    prototype: T;
}

```

**Comment by ahejlsberg** [comment]
Another type ordering issue. When inferring the type argument for the `inject(Store)` call, two inference candidates are produced: `Store<unknown>` and `Store<any>`. Those types are mutual subtypes, so inference picks the first candidate. However, the order of the candidates is determined by the order of the two types in the `ProviderToken<T>` union type, and that unfortunately differs between the old and the new compiler. You can observe the same error with the old compiler simply by reversing the order of the types in `ProviderToken<T>`.

Interestingly, when performing subtype reduction on union types, we use the strict subtype relation in which `any` is a supertype of `unknown`. We introduced the strict subtype relation specifically to reduce mutual subtype effects, but for some reason we never switched `getCommonSupertype` to use that relation. If we did, it would fix this issue. I'm running an experiment to see the effects of such a change [here](https://github.com/microsoft/TypeScript/pull/61903).
