### PR TITLE
Invalidate `--build` incremental cache when non-root program inputs like node_modules files change

### PR DESCRIPTION
**Pull request by christianvuerings**
Addresses #2666: `tsgo --build` reports a project as up to date after a dependency in `node_modules` is updated, even though the updated declaration files introduce type errors.

### Root cause

The up-to-date check in `getUpToDateStatus` only verifies the timestamps of the config root files (`t.resolved.FileNames()`). All other program inputs recorded in the buildinfo, such as `.d.ts` files resolved from `node_modules`, are never checked, so the incremental cache is not invalidated when they change. The buildinfo already records content hashes for every program file in `fileInfos`; they were just never consulted for non-root files. Resolution-affecting `package.json` files are not recorded at all (the strada port has a commented out `lastCachedPackageJsonLookups` TODO).

### Fix

After the existing root file checks, the up-to-date check now also verifies:

1. **Non-root program files recorded in the buildinfo.** A missing file (eg a removed or pruned package) marks the project out of date. A file newer than the buildinfo is re-hashed and compared against the recorded version; a mismatch marks the project out of date, while unchanged text only updates output timestamps (same pseudo-build treatment as root files). Bundled lib files are skipped since they only change with the compiler version, which `buildInfo.Version` already validates. File names that cannot be made relative to the buildinfo directory (eg on another drive) are resolved the same way the buildinfo reader resolves them, so they are checked rather than mistaken for lib files.

2. **`package.json` files used during module resolution.** The buildinfo now records the package.json files that exist and were consulted during resolution (a new `packageJsonLookups` field) along with a hash of their contents. The check compares contents by hash instead of timestamps, so it catches edits that redirect resolution (eg changing `types` or `exports`) as well as updates that keep old timestamps, such as an `npm install` repointing a `file:` symlink at a different target (the exact flavor in the minimal repro repo). Hashes are cached per build cycle so a package.json shared by many projects is only read once per invocation.

### Before / after

Repro from the issue (dependency `.d.ts` changes `myValue: string` to `myValue: number` while `dist/tsconfig.tsbuildinfo` exists):

```
# before (main)
$ tsgo --build tsconfig.json     # after dependency update
exit 0                           # bug: reports up to date, error never surfaces

# after (this PR)
$ tsgo --build tsconfig.json     # after dependency update
index.ts(2,14): error TS2322: Type 'number' is not assignable to type 'string'.
exit 2
```

The reproduction repo from https://github.com/rubenferreira97/tsgo_build_bug (npm `file:` symlink retarget) now also fails the incremental build correctly, caught by the package.json contents check.

A newer mtime with unchanged contents only triggers a timestamp update, and a no-op rebuild still reports up to date, so unchanged projects do not rebuild.

### Tests

`TestBuildDependencyUpdate` covers: dependency update with a breaking type change, restore, touch without text change, deletion of a dependency file, plus the two review cases: a package.json `types` redirect to a different declaration file, and an absolute (cross-drive) non-root dependency update.

Existing baseline changes are additive (`packageJsonLookups` in buildinfo) apart from three message-text improvements where the out-of-date status now names the precise changed upstream `.d.ts` instead of the referenced project directory.

### Not covered

- A package.json appearing at a location that was previously probed and missing (only existing package.json files are recorded, to keep the buildinfo small).
- Non-incremental `--build` projects, whose buildinfo does not record program file names, keep the existing roots-only behavior.
- Watch mode dependency watching is being reworked separately in #3670.

### Notes

- Cost for an up-to-date incremental project is one extra stat per recorded non-root program file, plus one read+hash per consulted package.json (cached per build cycle across projects). Program files are only read and hashed when their mtime is newer than the buildinfo.

### CODE REVIEW

**Comment by jakebailey** [comment]
Thanks for your PRs, but I think it's clear you're using an AI tool to do this. Can you explain what you're doing and how you've chosen these issues to fix? Are you personally experiencing these problems?

**Comment by christianvuerings** [comment]
> Thanks for your PRs, but I think it's clear you're using an AI tool to do this. Can you explain what you're doing and how you've chosen these issues to fix? Are you personally experiencing these problems?

Yes, these are bugs we're hitting at Airbnb. We are working on our migration from TS to TypeScript Go on a large monorepo, and this one is a blocker: incremental builds silently miss dependency updates, so we can't trust `tsgo --build` in CI or locally. Right now we work around it by deleting all `.tsbuildinfo` caches whenever the lockfile changes.

And yes, I use Claude Code to help write the fix, but I reproduced the bug myself, reviewed the change, and validated before/after behavior plus the full test suite. Happy to iterate or close it if you'd rather handle this differently.

**Comment by jakebailey** [comment]
Thanks for the context!

**Comment by jakebailey** [comment]
Here are two more test cases for `TestBuildDependencyUpdate` that show that this is incomplete (I had copilot generate them):

```go
{
			subScenario: "rebuilds when dependency package json redirects to a different declaration file",
			files: FileMap{
				"/home/src/workspaces/project/tsconfig.json": stringtestutil.Dedent(`
					{
						"compilerOptions": {
							"composite": true,
							"outDir": "dist",
							"strict": true
						},
						"include": ["src/**/*"]
					}
				`),
				"/home/src/workspaces/project/src/index.ts": stringtestutil.Dedent(`
					import { myValue } from "my-dep";
					export const value: string = myValue;
				`),
				"/home/src/workspaces/project/node_modules/my-dep/package.json": stringtestutil.Dedent(`
					{
						"name": "my-dep",
						"version": "1.0.0",
						"types": "index.d.ts"
					}
				`),
				"/home/src/workspaces/project/node_modules/my-dep/index.d.ts": "export declare const myValue: string;",
				"/home/src/workspaces/project/node_modules/my-dep/alt.d.ts":   "export declare const myValue: number;",
			},
			cwd:             "/home/src/workspaces/project",
			commandLineArgs: []string{"--b", "--verbose"},
			edits: []*tscEdit{
				{
					caption: "redirect package types to a declaration file with a breaking type change",
					edit: func(sys *TestSys) {
						sys.replaceFileText("/home/src/workspaces/project/node_modules/my-dep/package.json", "index.d.ts", "alt.d.ts")
					},
				},
			},
		},
		{
			subScenario: "rebuilds when absolute non-root dependency is updated",
			files: FileMap{
				"C:/work/project/tsconfig.json": stringtestutil.Dedent(`
					{
						"compilerOptions": {
							"composite": true,
							"outDir": "dist",
							"paths": {
								"abs-dep": ["D:/deps/dep.d.ts"]
							},
							"strict": true
						},
						"include": ["src/**/*"]
					}
				`),
				"C:/work/project/src/index.ts": stringtestutil.Dedent(`
					import { myValue } from "abs-dep";
					export const value: string = myValue;
				`),
				"D:/deps/dep.d.ts": "export declare const myValue: string;",
			},
			cwd:              "C:/work/project",
			windowsStyleRoot: "C:/",
			ignoreCase:       true,
			commandLineArgs:  []string{"--b", "--verbose"},
			edits: []*tscEdit{
				{
					caption: "update absolute non-root dependency with breaking type change",
					edit: func(sys *TestSys) {
						sys.writeFileNoError("D:/deps/dep.d.ts", "export declare const myValue: number;")
					},
				},
			},
		},
```

**Comment by jakebailey** [comment]
[patch.patch](https://github.com/user-attachments/files/28903229/patch.patch)
[patch2.patch](https://github.com/user-attachments/files/28903230/patch2.patch)

These two seem to look good (you might be doing the same thing too; just trying to make progress!)

**Comment by jakebailey** [comment]
But, I'm basically just recreating a bad version of #1686.

**Comment by jakebailey** [comment]
Possibly these are actually already broken on main, but, sort of related. Maybe not required. I'll look into reviving 1686

**Comment by jakebailey** [comment]
Oh, did you just pull 1686 into this? Or all new code? (no attribution?)

**Comment by jakebailey** [comment]
FWIW I made #4301; can you see if this fixes your issue? I'd rather stick with Sheetal's code for this.

**Comment by christianvuerings** [comment]
> Oh, did you just pull 1686 into this? Or all new code? (no attribution?)

All new code, I hadn't seen #1686. I worked off the `lastCachedPackageJsonLookups` TODO and converged on the same idea, though mine hashes contents rather than checking timestamps.

> FWIW I made https://github.com/microsoft/typescript-go/pull/4301; can you see if this fixes your issue? I'd rather stick with Sheetal's code for this.

I confirmed #4301 fixes our repro including the `file:` symlink retarget case. Happy to go with Sheetal's / yours, thanks for reviving it!

Going to close this PR for now. Feel free to (re-)use any code that I posted in here.
